Write-Output "┌> How To Run Example: MasterParser.ps1 -O Start"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
Write-Output "│                               Options (-O)                               │"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
Write-Output "│                                                                          │"
Write-Output "│1. Start        Run the tool by parsing all the logs under logs folder    │"
Write-Output "│                                                                          │"
Write-Output "│2. Menu         Show menu of what you can do with MasterParser tool       │"
Write-Output "│                                                                          │"
Write-Output "│3. Update       Update MasterParser to the latest version                 │"
Write-Output "│                                                                          │"
Write-Output "│4. Purge        Purge MasterParser tool footprint from this host          │"
Write-Output "│                                                                          │"
Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
Write-Output ""