

Write-Output "┌> How To Run Example: MasterParser.ps1 -Option Update"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
Write-Output "│                               Options (-Options)                         │"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
Write-Output "│                                                                          │"
Write-Output "│1. Start        Run the tool by parsing all the logs under logs folder    │"
Write-Output "│                                                                          │"
Write-Output "│2. Menu         Show menu of what you can do with MasterParser tool       │"
Write-Output "│                                                                          │"
Write-Output "│3. Update       Update MasterParser to the latest version                 │"
Write-Output "│                                                                          │"
Write-Output "│4. Purge        Purge MasterParser tool footprint from this host          │"
Write-Output "│                                                                          │"
Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
Write-Output ""
Write-Output ""
Write-Output "┌> How To Run Example: MasterParser.ps1 -Option Start -Type All"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
Write-Output "│                               Type (-Type)                               │"
Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
Write-Output "│                                                                          │"
Write-Output "│1. All          Results will be outputted as Raw events and as Statistics │"
Write-Output "│                                                                          │"
Write-Output "│2. Raw          Results will be outputted as raw events only              │"
Write-Output "│                                                                          │"
Write-Output "│3. Statistics   Results will be outputted as statistics tables only       │"
Write-Output "│                                                                          │"
Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
Write-Output ""